# Generated by Django 4.2.13 on 2024-07-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MangaVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manga')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateField()),
                ('position', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('manga_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mangavolume')),
            ],
        ),
    ]
